on: 
   push:
        branches:
               - master
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ftp.bableshaazad.com
        # username: ${{ secrets.ftp_username }}
        username: bablesha
        # password: ${{ secrets.ftp_password }}
        password: AAzad@8817
        server-dir: /home/bablesha/repositories/BableshAAzad.com-new/public/index.html/
